version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: >
      bash -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: library_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
