# Generated by Django 4.2.20 on 2025-03-28 04:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BorrowTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrowed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("return_date", models.DateField()),
                ("returned", models.BooleanField(default=False)),
                (
                    "penalty",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
            ],
        ),
    ]
