# Generated by Django 4.2.20 on 2025-04-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrow", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowtransaction",
            name="borrowed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
